// <auto-generated />
using System;
using ECommerce.FlashSaleOrchestrator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.FlashSaleOrchestrator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlashSaleOrchestratorDbContext))]
    [Migration("20260813133315_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.FlashSales.FlashSale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("FlashSales", (string)null);
                });

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int")
                        .HasColumnName("AvailableQuantity");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProductId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.Carts.Cart", b =>
                {
                    b.OwnsMany("ECommerce.FlashSaleOrchestrator.Domain.Carts.CartItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("CartId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("CartItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("ECommerce.FlashSaleOrchestrator.Domain.Products.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.FlashSales.FlashSale", b =>
                {
                    b.OwnsMany("ECommerce.FlashSaleOrchestrator.Domain.FlashSales.FlashSaleEligibleProduct", "EligibleProducts", b1 =>
                        {
                            b1.Property<Guid>("FlashSaleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("FlashSaleId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("FlashSaleEligibleProducts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FlashSaleId");

                            b1.HasOne("ECommerce.FlashSaleOrchestrator.Domain.Products.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("EligibleProducts");
                });

            modelBuilder.Entity("ECommerce.FlashSaleOrchestrator.Domain.Inventory.InventoryItem", b =>
                {
                    b.HasOne("ECommerce.FlashSaleOrchestrator.Domain.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("ECommerce.FlashSaleOrchestrator.Domain.Inventory.InventoryItem", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
